### ISSUE TITLE
How can i customize the buttons.. they are too big 

### ISSUE THREAD

**Issue by ItzNinjaHo** [HealKnix/macos-titlebar-for-windows#1]
i installed your extension and the buttons appeared but they were blurry and too big. i need a way to make them smaller. ( sorry for bad english )
![Screenshot (5)](https://github.com/HealKnix/macos-titlebar-for-windows/assets/110479061/5c7200c4-9592-43ea-8946-1fb64d17fb42)

**Comment by HealKnix** [comment]
Hi. Thanks for using my extension!)
If you want to change the button size, go to JSON user settings (use `ctrl + shift + p` and type "Preferences: Open User Settings (JSON)").
Find 2 values: ".window-icon:hover::after" and ".window-icon::before"; and change their `width` and `height` properties.
I recommend changing them so that ".window-icon:hover::after" has 2 pixels less than ".window-icon::before".
Enjoy :)

**Comment by ItzNinjaHo** [comment]
Thanks!
